### ISSUE TITLE
precompile fail on M1

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaPlots/GeoMakie.jl#104]
Proj4 is causing an install failure for GeoMakie on M1 with either 1.7.2 or 1.8-beta3 https://github.com/JuliaGeo/Proj4.jl/issues/61

**Comment by asinghvi17** [comment]
Yep, that's expected - Proj4 has a PR and a rename which will add M1 support at https://github.com/JuliaGeo/Proj4.jl/pull/57.  Because it is a rename, though, it's a bit complicated to install.  If you're comfortable fiddling around a bit (totally reversible), you can do the following in terminal:

```bash
cd ~/.julia/
mkdir -p dev
cd dev
git clone https://github.com/JuliaGeo/Proj4.jl Proj
cd Proj
git checkout rename
popd; popd; popd # go back to where you were
```
Then, in Julia, run the following:
```julia
using Pkg
pkg"dev ~/.julia/Proj; add GeoMakie#as/geoaxis"
```

After this, you should be able to `using GeoMakie` normally.  Note that GLMakie will likely not work, though, so you'll have to use CairoMakie or WGLMakie (I recommend Cairo).

Best of luck!  I'm on an M1 mac too so I feel your pain :), but we should be able to get to full support in a couple of weeks.
