### ISSUE TITLE
How to plot coastlines?

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GeoMakie.jl#8]
Let's say I plot some whatever random field in my plot of the earth, like
```
using GeoMakie, Makie, Proj4
lons = 0.5:1:359.5
lats = -89.5:1:89.5
field = [sind(l)^2 + (y/90)^2 for l in lons, y in lats, i in 1:5] # not my actual data, but this will do
source = WGS84()
dest = Projection("+proj=moll +lon_0=+180")
points = GeoMakie.transform.(WGS84(), dest, GeoMakie.gridpoints(lons, lats))
faces  = GeoMakie.grid_triangle_faces(lons, lats)
colorfunc(i) = vec(field[:, :, i])
scene = poly(points, faces; color = colorfunc(1), show_axis = false)
geoaxis!(scene, -180, 180, -90, 90; crs = (dest = dest,))
```
![image](https://user-images.githubusercontent.com/19669089/72645649-6fa07e00-3974-11ea-907b-3a9c11468750.png)

How do I plot the coastlines on top of that, which I think it is the only way to decide if I am using correctly my longitude and lattitude?

**Comment by asinghvi17** [comment]
If you get the Natural Earth data you can load it in, transform it using rec_transform, and plot it using lines - see the coastlines.jl file in tests.

**Comment by asinghvi17** [comment]
I'm creating a repo to serve up tarballs of the Natural Earth data as GeoJSON, which you can then download (I might store them as artifacts).  This will allow, e.g., a `coastlines` recipe to exist.  The problem now is that coordinate reference systems are a bit of a pain, since they aren't easily accessible in axes.  Currently you have to specify destination CRS every time.

**Comment by visr** [comment]
@asinghvi17 the people behind Natural Earth are already serving GeoJSON from their repo: https://github.com/nvkelso/natural-earth-vector/tree/master/geojson

Ddding Natural Earth to https://github.com/JuliaGeo/GeoDatasets.jl or using the new artifact system may also be an option.

**Comment by asinghvi17** [comment]
Yeah, I was going to use that repo actually - the problem is that to use artifacts you need a source of tarballs, which you can't download from Github (I think).  What I was going to do is essentially get all the geojson files they put up and create individual artifacts for each of them (and mark all except the 110m coastlines one lazy).  That would probably fit in very well with GeoDatasets, but it would require 1.3 compat, so I'm tempted to just make a separate package.

**Comment by visr** [comment]
Ah ok great you found it already. Indeed I think you need to repack them yourself then. Would be a nice package to have. Not sure if GeoDatasets needs below 1.3 support, but we can always integrate it later as well.

This script may help a bit to generate the artifacts: https://github.com/JuliaGeo/Proj4.jl/pull/33/commits/9345210677964d31b49cecbe2de4ddfce80ca802

**Comment by asinghvi17** [comment]
@visr, how did you generate the sha256s for your artifacts?

**Comment by visr** [comment]
Manually in Total Commander on Windows. But you can also let the script calculate them. I think BinaryProvider has alternatives to download_verify_unpack.

**Comment by visr** [comment]
Heads up for GeoJSON.jl, I just tagged the new release that makes the switch to JSON3: https://github.com/JuliaGeo/GeoJSON.jl/pull/24

**Comment by asinghvi17** [comment]
I've decided to take the short route and just bundle the data with the repo - now, `coastlines!(; crs = (dest = dest,))` should just work!
